baseurl = "http://www.mthaneman.xyz"
title = "Michael Haneman"
theme = "showoff-theme"

[params]
  author = "Michael Haneman"
  info = "Test Automation Engineer at Boeing"
  description = "Michael Haneman's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Menu links
[[menus.main]]
name = "Articles"
weight = 10
pageRef  = "articles/"

[[menus.main]]
name = "Experience"
weight = 20
pageRef = "about/"

[[menus.main]]
name = "Projects"
weight = 30
pageRef = "projects/"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/mhaneman" 

[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/mhaneman" 

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/michael-haneman-1062461a4/" 

